services:
  # Backend API Service
  - type: web
    name: manus-clone-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_API_BASE
        value: https://api.openai.com/v1
      - key: CORS_ORIGIN
        value: https://manus-clone-frontend.onrender.com

  # Frontend Service
  - type: web
    name: manus-clone-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://manus-clone-backend.onrender.com/api
      - key: VITE_SOCKET_URL
        value: https://manus-clone-backend.onrender.com
      - key: VITE_APP_NAME
        value: Manus Clone
      - key: VITE_APP_VERSION
        value: 1.0.0